/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_noisepages_nettoyeur_patchbay_Patchbay */

#ifndef _Included_com_noisepages_nettoyeur_patchbay_Patchbay
#define _Included_com_noisepages_nettoyeur_patchbay_Patchbay
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_noisepages_nettoyeur_patchbay_Patchbay
 * Method:    createInstance
 * Signature: (IIII)J
 */
JNIEXPORT jlong JNICALL Java_com_noisepages_nettoyeur_patchbay_Patchbay_createInstance
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_noisepages_nettoyeur_patchbay_Patchbay
 * Method:    sendSharedMemoryFileDescriptor
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_noisepages_nettoyeur_patchbay_Patchbay_sendSharedMemoryFileDescriptor
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_noisepages_nettoyeur_patchbay_Patchbay
 * Method:    releaseInstance
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_noisepages_nettoyeur_patchbay_Patchbay_releaseInstance
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_noisepages_nettoyeur_patchbay_Patchbay
 * Method:    createModule
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_com_noisepages_nettoyeur_patchbay_Patchbay_createModule
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_noisepages_nettoyeur_patchbay_Patchbay
 * Method:    deleteModule
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_noisepages_nettoyeur_patchbay_Patchbay_deleteModule
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_noisepages_nettoyeur_patchbay_Patchbay
 * Method:    connectModules
 * Signature: (JIIII)I
 */
JNIEXPORT jint JNICALL Java_com_noisepages_nettoyeur_patchbay_Patchbay_connectModules
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     com_noisepages_nettoyeur_patchbay_Patchbay
 * Method:    disconnectModules
 * Signature: (JIIII)I
 */
JNIEXPORT jint JNICALL Java_com_noisepages_nettoyeur_patchbay_Patchbay_disconnectModules
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     com_noisepages_nettoyeur_patchbay_Patchbay
 * Method:    activateModule
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_noisepages_nettoyeur_patchbay_Patchbay_activateModule
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_noisepages_nettoyeur_patchbay_Patchbay
 * Method:    deactivateModule
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_noisepages_nettoyeur_patchbay_Patchbay_deactivateModule
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_noisepages_nettoyeur_patchbay_Patchbay
 * Method:    start
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_noisepages_nettoyeur_patchbay_Patchbay_start
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_noisepages_nettoyeur_patchbay_Patchbay
 * Method:    stop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_noisepages_nettoyeur_patchbay_Patchbay_stop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_noisepages_nettoyeur_patchbay_Patchbay
 * Method:    isActive
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_noisepages_nettoyeur_patchbay_Patchbay_isActive
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_noisepages_nettoyeur_patchbay_Patchbay
 * Method:    isRunning
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_noisepages_nettoyeur_patchbay_Patchbay_isRunning
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_noisepages_nettoyeur_patchbay_Patchbay
 * Method:    isConnected
 * Signature: (JIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_noisepages_nettoyeur_patchbay_Patchbay_isConnected
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     com_noisepages_nettoyeur_patchbay_Patchbay
 * Method:    getInputChannels
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_noisepages_nettoyeur_patchbay_Patchbay_getInputChannels
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_noisepages_nettoyeur_patchbay_Patchbay
 * Method:    getOutputChannels
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_noisepages_nettoyeur_patchbay_Patchbay_getOutputChannels
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
