/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_noisepages_nettoyeur_patchfield_source_PcmSource */

#ifndef _Included_com_noisepages_nettoyeur_patchfield_source_PcmSource
#define _Included_com_noisepages_nettoyeur_patchfield_source_PcmSource
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_noisepages_nettoyeur_patchfield_source_PcmSource
 * Method:    createSource
 * Signature: (JLjava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_com_noisepages_nettoyeur_patchfield_source_PcmSource_createSource
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_noisepages_nettoyeur_patchfield_source_PcmSource
 * Method:    release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_noisepages_nettoyeur_patchfield_source_PcmSource_release
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
