/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_noisepages_nettoyeur_patchbay_lowpass_LowpassModule */

#ifndef _Included_com_noisepages_nettoyeur_patchbay_lowpass_LowpassModule
#define _Included_com_noisepages_nettoyeur_patchbay_lowpass_LowpassModule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_noisepages_nettoyeur_patchbay_lowpass_LowpassModule
 * Method:    getMaxChannels
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_noisepages_nettoyeur_patchbay_lowpass_LowpassModule_getMaxChannels
  (JNIEnv *, jclass);

/*
 * Class:     com_noisepages_nettoyeur_patchbay_lowpass_LowpassModule
 * Method:    setParameter
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_com_noisepages_nettoyeur_patchbay_lowpass_LowpassModule_setParameter
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     com_noisepages_nettoyeur_patchbay_lowpass_LowpassModule
 * Method:    createModule
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_noisepages_nettoyeur_patchbay_lowpass_LowpassModule_createModule
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_noisepages_nettoyeur_patchbay_lowpass_LowpassModule
 * Method:    release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_noisepages_nettoyeur_patchbay_lowpass_LowpassModule_release
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
