/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_noisepages_nettoyeur_patchbay_samples_IdentityModule */

#ifndef _Included_com_noisepages_nettoyeur_patchbay_samples_IdentityModule
#define _Included_com_noisepages_nettoyeur_patchbay_samples_IdentityModule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_noisepages_nettoyeur_patchbay_samples_IdentityModule
 * Method:    createModule
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_noisepages_nettoyeur_patchbay_samples_IdentityModule_createModule
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_noisepages_nettoyeur_patchbay_samples_IdentityModule
 * Method:    release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_noisepages_nettoyeur_patchbay_samples_IdentityModule_release
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_noisepages_nettoyeur_patchbay_samples_IdentityModule
 * Method:    hasTimedOut
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_noisepages_nettoyeur_patchbay_samples_IdentityModule_hasTimedOut
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
