/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_noisepages_nettoyeur_patchbay_samples_LowpassModule */

#ifndef _Included_com_noisepages_nettoyeur_patchbay_samples_LowpassModule
#define _Included_com_noisepages_nettoyeur_patchbay_samples_LowpassModule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_noisepages_nettoyeur_patchbay_samples_LowpassModule
 * Method:    getProtocolVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_noisepages_nettoyeur_patchbay_samples_LowpassModule_getProtocolVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_noisepages_nettoyeur_patchbay_samples_LowpassModule
 * Method:    getMaxChannels
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_noisepages_nettoyeur_patchbay_samples_LowpassModule_getMaxChannels
  (JNIEnv *, jclass);

/*
 * Class:     com_noisepages_nettoyeur_patchbay_samples_LowpassModule
 * Method:    setParameter
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_com_noisepages_nettoyeur_patchbay_samples_LowpassModule_setParameter
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     com_noisepages_nettoyeur_patchbay_samples_LowpassModule
 * Method:    createModule
 * Signature: (IIII)J
 */
JNIEXPORT jlong JNICALL Java_com_noisepages_nettoyeur_patchbay_samples_LowpassModule_createModule
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_noisepages_nettoyeur_patchbay_samples_LowpassModule
 * Method:    release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_noisepages_nettoyeur_patchbay_samples_LowpassModule_release
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_noisepages_nettoyeur_patchbay_samples_LowpassModule
 * Method:    hasTimedOut
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_noisepages_nettoyeur_patchbay_samples_LowpassModule_hasTimedOut
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
