/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_noisepages_nettoyeur_patchfield_PatchField */

#ifndef _Included_com_noisepages_nettoyeur_patchfield_PatchField
#define _Included_com_noisepages_nettoyeur_patchfield_PatchField
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_noisepages_nettoyeur_patchfield_PatchField
 * Method:    createInstance
 * Signature: (IIII)J
 */
JNIEXPORT jlong JNICALL Java_com_noisepages_nettoyeur_patchfield_PatchField_createInstance
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_noisepages_nettoyeur_patchfield_PatchField
 * Method:    sendSharedMemoryFileDescriptor
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_noisepages_nettoyeur_patchfield_PatchField_sendSharedMemoryFileDescriptor
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_noisepages_nettoyeur_patchfield_PatchField
 * Method:    releaseInstance
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_noisepages_nettoyeur_patchfield_PatchField_releaseInstance
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_noisepages_nettoyeur_patchfield_PatchField
 * Method:    createModule
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_com_noisepages_nettoyeur_patchfield_PatchField_createModule
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_noisepages_nettoyeur_patchfield_PatchField
 * Method:    deleteModule
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_noisepages_nettoyeur_patchfield_PatchField_deleteModule
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_noisepages_nettoyeur_patchfield_PatchField
 * Method:    connectPorts
 * Signature: (JIIII)I
 */
JNIEXPORT jint JNICALL Java_com_noisepages_nettoyeur_patchfield_PatchField_connectPorts
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     com_noisepages_nettoyeur_patchfield_PatchField
 * Method:    disconnectPorts
 * Signature: (JIIII)I
 */
JNIEXPORT jint JNICALL Java_com_noisepages_nettoyeur_patchfield_PatchField_disconnectPorts
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     com_noisepages_nettoyeur_patchfield_PatchField
 * Method:    activateModule
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_noisepages_nettoyeur_patchfield_PatchField_activateModule
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_noisepages_nettoyeur_patchfield_PatchField
 * Method:    deactivateModule
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_noisepages_nettoyeur_patchfield_PatchField_deactivateModule
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_noisepages_nettoyeur_patchfield_PatchField
 * Method:    start
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_noisepages_nettoyeur_patchfield_PatchField_start
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_noisepages_nettoyeur_patchfield_PatchField
 * Method:    stop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_noisepages_nettoyeur_patchfield_PatchField_stop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_noisepages_nettoyeur_patchfield_PatchField
 * Method:    isActive
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_noisepages_nettoyeur_patchfield_PatchField_isActive
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_noisepages_nettoyeur_patchfield_PatchField
 * Method:    isRunning
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_noisepages_nettoyeur_patchfield_PatchField_isRunning
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_noisepages_nettoyeur_patchfield_PatchField
 * Method:    isConnected
 * Signature: (JIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_noisepages_nettoyeur_patchfield_PatchField_isConnected
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     com_noisepages_nettoyeur_patchfield_PatchField
 * Method:    getInputChannels
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_noisepages_nettoyeur_patchfield_PatchField_getInputChannels
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_noisepages_nettoyeur_patchfield_PatchField
 * Method:    getOutputChannels
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_noisepages_nettoyeur_patchfield_PatchField_getOutputChannels
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_noisepages_nettoyeur_patchfield_PatchField
 * Method:    getProtocolVersion
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_noisepages_nettoyeur_patchfield_PatchField_getProtocolVersion
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
