/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_noisepages_nettoyeur_patchfield_Patchfield */

#ifndef _Included_com_noisepages_nettoyeur_patchfield_Patchfield
#define _Included_com_noisepages_nettoyeur_patchfield_Patchfield
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_noisepages_nettoyeur_patchfield_Patchfield
 * Method:    createInstance
 * Signature: (IIII)J
 */
JNIEXPORT jlong JNICALL Java_com_noisepages_nettoyeur_patchfield_Patchfield_createInstance
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_noisepages_nettoyeur_patchfield_Patchfield
 * Method:    sendSharedMemoryFileDescriptor
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_noisepages_nettoyeur_patchfield_Patchfield_sendSharedMemoryFileDescriptor
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_noisepages_nettoyeur_patchfield_Patchfield
 * Method:    releaseInstance
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_noisepages_nettoyeur_patchfield_Patchfield_releaseInstance
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_noisepages_nettoyeur_patchfield_Patchfield
 * Method:    createModule
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_com_noisepages_nettoyeur_patchfield_Patchfield_createModule
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_noisepages_nettoyeur_patchfield_Patchfield
 * Method:    deleteModule
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_noisepages_nettoyeur_patchfield_Patchfield_deleteModule
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_noisepages_nettoyeur_patchfield_Patchfield
 * Method:    connectPorts
 * Signature: (JIIII)I
 */
JNIEXPORT jint JNICALL Java_com_noisepages_nettoyeur_patchfield_Patchfield_connectPorts
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     com_noisepages_nettoyeur_patchfield_Patchfield
 * Method:    disconnectPorts
 * Signature: (JIIII)I
 */
JNIEXPORT jint JNICALL Java_com_noisepages_nettoyeur_patchfield_Patchfield_disconnectPorts
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     com_noisepages_nettoyeur_patchfield_Patchfield
 * Method:    activateModule
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_noisepages_nettoyeur_patchfield_Patchfield_activateModule
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_noisepages_nettoyeur_patchfield_Patchfield
 * Method:    deactivateModule
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_noisepages_nettoyeur_patchfield_Patchfield_deactivateModule
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_noisepages_nettoyeur_patchfield_Patchfield
 * Method:    start
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_noisepages_nettoyeur_patchfield_Patchfield_start
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_noisepages_nettoyeur_patchfield_Patchfield
 * Method:    stop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_noisepages_nettoyeur_patchfield_Patchfield_stop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_noisepages_nettoyeur_patchfield_Patchfield
 * Method:    isActive
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_noisepages_nettoyeur_patchfield_Patchfield_isActive
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_noisepages_nettoyeur_patchfield_Patchfield
 * Method:    isRunning
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_noisepages_nettoyeur_patchfield_Patchfield_isRunning
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_noisepages_nettoyeur_patchfield_Patchfield
 * Method:    isConnected
 * Signature: (JIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_noisepages_nettoyeur_patchfield_Patchfield_isConnected
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     com_noisepages_nettoyeur_patchfield_Patchfield
 * Method:    getInputChannels
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_noisepages_nettoyeur_patchfield_Patchfield_getInputChannels
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_noisepages_nettoyeur_patchfield_Patchfield
 * Method:    getOutputChannels
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_noisepages_nettoyeur_patchfield_Patchfield_getOutputChannels
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_noisepages_nettoyeur_patchfield_Patchfield
 * Method:    getProtocolVersion
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_noisepages_nettoyeur_patchfield_Patchfield_getProtocolVersion
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
