/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_noisepages_nettoyeur_patchbay_pd_PdModule */

#ifndef _Included_com_noisepages_nettoyeur_patchbay_pd_PdModule
#define _Included_com_noisepages_nettoyeur_patchbay_pd_PdModule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_noisepages_nettoyeur_patchbay_pd_PdModule
 * Method:    pdInitAudio
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_noisepages_nettoyeur_patchbay_pd_PdModule_pdInitAudio
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_noisepages_nettoyeur_patchbay_pd_PdModule
 * Method:    hasTimedOut
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_noisepages_nettoyeur_patchbay_pd_PdModule_hasTimedOut
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_noisepages_nettoyeur_patchbay_pd_PdModule
 * Method:    getProtocolVersion
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_noisepages_nettoyeur_patchbay_pd_PdModule_getProtocolVersion
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_noisepages_nettoyeur_patchbay_pd_PdModule
 * Method:    configureModule
 * Signature: (IIIIIII)J
 */
JNIEXPORT jlong JNICALL Java_com_noisepages_nettoyeur_patchbay_pd_PdModule_configureModule
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_noisepages_nettoyeur_patchbay_pd_PdModule
 * Method:    release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_noisepages_nettoyeur_patchbay_pd_PdModule_release
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
