/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_noisepages_nettoyeur_patchfield_messagesample_MessageModule */

#ifndef _Included_com_noisepages_nettoyeur_patchfield_messagesample_MessageModule
#define _Included_com_noisepages_nettoyeur_patchfield_messagesample_MessageModule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_noisepages_nettoyeur_patchfield_messagesample_MessageModule
 * Method:    configureNativeComponents
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_noisepages_nettoyeur_patchfield_messagesample_MessageModule_configureNativeComponents
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_noisepages_nettoyeur_patchfield_messagesample_MessageModule
 * Method:    release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_noisepages_nettoyeur_patchfield_messagesample_MessageModule_release
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
