/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_noisepages_nettoyeur_patchbay_modules_IdentityModule */

#ifndef _Included_com_noisepages_nettoyeur_patchbay_modules_IdentityModule
#define _Included_com_noisepages_nettoyeur_patchbay_modules_IdentityModule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_noisepages_nettoyeur_patchbay_modules_IdentityModule
 * Method:    configure
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_noisepages_nettoyeur_patchbay_modules_IdentityModule_configure
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
